### PR TITLE
Added simple installer - first go

### PR DESCRIPTION
**Pull request by Tdue21**
I have added a simple installer. I have not completed my vision for the installer, but it is fully functional. 
This is in reference to #47.

### CODE REVIEW

**Comment by Tdue21** [comment]
I believe an initial installer with bootstrapper and .NET Framework 4.5 check is complete.

**Comment by jijiechen** [comment]
Awesome idea!

**Comment by Jaben** [comment]
@Tdue21 Been on vacation -- will test this week. FYI Papercut still supports .NET v4.0 (because windows xp)

**Comment by Tdue21** [comment]
Right. I do not agree with supporting Windows XP. But that is your call :)

**Comment by Tdue21** [comment]
Updated the installer bundle here https://github.com/Tdue21/Papercut/releases/download/4.8-installer/Papercut.Setup.exe to the new requirements 😄 
I.e. MSI 3.1 and .NET 4.0 (Support for Windows XP SP3).

**Comment by Jaben** [comment]
Tested it... great effort so far -- slick! 

One issue I see, though, is lack of permissions for the incoming directory:

```[Error] Failure accessing or creating directory "C:\Program Files (x86)\Changemaker Studios\Papercut\Incoming" Exception: Access to the path 'C:\Program Files (x86)\Changemaker Studios\Papercut\Incoming' is denied.```

It will still work without that permission -- but it would be better if it was setup by the installer.

**Comment by Tdue21** [comment]
Not a problem, I'll do that tonight. What kind of permissions do you need? And just for folder Incoming?

**Comment by Jaben** [comment]
Fantastic. Yeah -- "user" permission so they don't have to run Papercut with elevated permissions.

**Comment by Tdue21** [comment]
Right, I'll look into it.

**Comment by Tdue21** [comment]
I accidentally made the changes in the bus going to work. Check out the new installer, if it suits you? 😄 

https://github.com/Tdue21/Papercut/releases/download/4.8-installer/Papercut.Setup.exe

**Comment by Jaben** [comment]
The reason I haven't merged this is that I'd like to have one installation solution going forward. My preference is something that will support automatic updates, etc such as https://github.com/Squirrel/Squirrel.Windows.

**Comment by Jaben** [comment]
Also I'd like it support installation of the service as a basic component option.

**Comment by Tdue21** [comment]
@Jaben it already has the service as a component and will install it as a Windows service.

**Comment by Jaben** [comment]
@Tdue21 Oh it does? Is it optional?

**Comment by Tdue21** [comment]
As I recall yes.

**Comment by Tdue21** [comment]
Screenshot of the feature page in the installation wizard: 

image

**Comment by Tdue21** [comment]
With regard to the auto update, then that could be achieved with something like Squirrel, I believe that the entire installation package should use this then though. 

Personally I prefer to handle updating myself, but I like to be advised when an update is available. 

This would be relatively simple to implement. A single file, either on a github page, or even in the repos, which is updated when an update is available. E.g.: 

https://github.com/ChangemakerStudios/Papercut/blob/master/current_version.xml
```
<?xml="1.0" encoding="utf8"?>
<Version>
    <Current>5.0.0.0</Current>
    <Link>https://github.com/ChangemakerStudios/Papercut/releases/download/5.0-installer/Papercut.Setup.exe</Link>
</Version
```
A sub-routine in either the application or the service could then check for this file on startup, or other regular interval and when the version in the file is different, then it will offer to download, or even do it automatically. 

I wouldn't think this required a lot of code, where as something like Squirrel is somewhat overkill. 

Your call though 😄

**Comment by jijiechen** [comment]
@Tdue21  Could you also add the newly added `Papercut.Module.WebUI` as a choice in the optional plugin list?

**Comment by Tdue21** [comment]
@jijiechen I'll look into it.

**Comment by Jaben** [comment]
You make good points @Tdue21 -- I will evaluate the current setup and merge this weekend. Thank you for all your help so far.

**Comment by Tdue21** [comment]
De nada :-)

**Comment by Tdue21** [comment]
Awesome. I am looking into making an Auto Update module. I will make it as a new pull request when I am satisfied 😄

**Comment by Jaben** [comment]
@Tdue21 v5 release now has a new Setup.exe :) Worked!

**Comment by jijiechen** [comment]
It seems my new pull request has missed this new release.

**Pull request merged**
