### PR TITLE
Basic web ui features

### PR DESCRIPTION
**Pull request by jijiechen**
In these change sets, we were trying to add a web UI for Papercut.
We added a Papercut.WebUI plugin project and the server will be booted by the "PapercutServiceReadyEvent" event. To ensure our implementation works as expected, we also added a test project, the Papercut.WebUI.Test project, which was powered by xunit.
The frontend material came from the MailHog project, it was powered by AngularJS 1.3 version. Despite the framework is now a bit out dated, we just reused it to make our work done sooner.

Additionally, we changed some small codes to add testability for the solution. Thanks to the DI framework and event based architecture, this work was done easily.

Please review and give your feedback, and merge this into trunk at your convenience.
Finally, many thanks to the great idea of Papercut, and the possibilities it gives to people.

@amymengfan @Stack-Coding Please subscribe to this thread as well.

### CODE REVIEW

**Comment by jijiechen** [comment]
@Jaben Very good point in your question.
The web UI is booted up by a handler of 'PapercutServiceReadyEvent' event, it seems this event is only fired in the Windows service, but not the desktop app.
I think we discuss how we can make it work for both desktop mode and background mode.

**Comment by jijiechen** [comment]
Now the web ui is launched with both desktop mode and Windows service mode.

**Comment by Jaben** [comment]
@jijiechen This is a wonderful effort. Really excellent. Merging.

**Comment by jjchen-tw** [comment]
@Jaben  Sorry for breaking the CI. I'll take some time on the issues as well.

**Pull request merged**
